import { NextRequest, NextResponse } from 'next/server';
import { google } from 'googleapis';
import { createServerClient } from '@supabase/ssr';
import fs from 'fs';
import path from 'path';
import os from 'os';

// Helper to download the video locally
async function downloadFile(url: string, outputPath: string) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.statusText}`);
  
  const arrayBuffer = await response.arrayBuffer();
  fs.writeFileSync(outputPath, new Uint8Array(arrayBuffer));
}

export async function POST(request: NextRequest) {
  try {
    const { storyId } = await request.json();
    if (!storyId) return NextResponse.json({ error: 'storyId is required' }, { status: 400 });

    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() {
            return request.cookies.getAll();
          },
          setAll() {},
        },
      }
    );

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    // Get YouTube refresh token
    const { data: settings } = await supabase
      .from('user_settings')
      .select('youtube_refresh_token')
      .eq('user_id', user.id)
      .single();

    if (!settings || !settings.youtube_refresh_token) {
      return NextResponse.json({ error: 'YouTube account not connected' }, { status: 400 });
    }

    // Get Story Data
    const { data: story } = await supabase
      .from('stories')
      .select('*, scenes(*)')
      .eq('id', storyId)
      .single();

    if (!story || !story.video_url) {
      return NextResponse.json({ error: 'Story or video not found' }, { status: 404 });
    }

    // Setup YouTube client
    const oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID,
      process.env.GOOGLE_CLIENT_SECRET
    );
    oauth2Client.setCredentials({ refresh_token: settings.youtube_refresh_token });
    const youtube = google.youtube({ version: 'v3', auth: oauth2Client });

    // Download video locally for upload
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'yt-upload-'));
    const videoPath = path.join(tmpDir, `video_${storyId}.mp4`);
    
    console.log('Downloading video for YouTube upload...');
    await downloadFile(story.video_url, videoPath);

    // Compile description from scenes
    const sortedScenes = story.scenes.sort((a: any, b: any) => a.scene_number - b.scene_number);
    const fullScript = sortedScenes.map((s: any) => `Scene ${s.scene_number}:\n${s.script}`).join('\n\n');

    console.log('Uploading to YouTube...');
    const res = await youtube.videos.insert({
      part: ['snippet', 'status'],
      requestBody: {
        snippet: {
          title: story.title || 'AI Generated Storyboard',
          description: `Generated by AI Storyboard Generator\n\n${fullScript}`,
          tags: ['AI', 'Storyboard', 'AI Video'],
        },
        status: {
          privacyStatus: 'private', // User requested private first
        },
      },
      media: {
        body: fs.createReadStream(videoPath),
      },
    });

    const videoId = res.data.id;
    const youtubeUrl = `https://www.youtube.com/watch?v=${videoId}`;

    // Clean up temp file
    fs.rmSync(tmpDir, { recursive: true, force: true });

    // Update story in DB
    await supabase
      .from('stories')
      .update({ youtube_url: youtubeUrl })
      .eq('id', storyId);

    return NextResponse.json({ success: true, youtubeUrl });

  } catch (error: any) {
    console.error('YouTube upload error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
