import { NextRequest, NextResponse } from 'next/server';
import { google } from 'googleapis';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { YouTubeUploadSchema } from '@/lib/validations';
import { getAuthenticatedUser, verifyStoryOwnership, validateMediaUrl } from '@/lib/auth-helpers';

// Helper to download the video locally with SSRF protection
async function downloadFile(url: string, outputPath: string) {
  if (!validateMediaUrl(url)) {
    throw new Error(`Invalid or disallowed video URL: ${url}`);
  }

  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.statusText}`);
  
  const arrayBuffer = await response.arrayBuffer();
  fs.writeFileSync(outputPath, new Uint8Array(arrayBuffer));
}

function sanitizePathComponent(input: string): string {
  return input.replace(/[^a-zA-Z0-9_-]/g, '');
}

export async function POST(request: NextRequest) {
  let userId: string | null = null;
  let currentChannelType: 'main' | 'sub' = 'main';
  let supabaseClient: any = null;
  let tmpDir: string | null = null;

  try {
    // 1. Authenticate user
    const { supabase, user } = await getAuthenticatedUser(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    userId = user.id;
    supabaseClient = supabase;

    // 2. Validate input
    let body: any;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ error: 'Invalid JSON payload' }, { status: 400 });
    }

    const validation = YouTubeUploadSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { error: validation.error.errors[0]?.message || 'Validation error' },
        { status: 400 }
      );
    }

    const { storyId, channelType } = validation.data;
    currentChannelType = channelType;

    // 3. Authorize story ownership (IDOR check)
    const story = await verifyStoryOwnership(supabase, storyId, user.id);
    if (!story || !story.video_url) {
      return NextResponse.json({ error: 'Story or video not found, or unauthorized' }, { status: 404 });
    }

    // 4. Get YouTube refresh token
    const { data: settings } = await supabase
      .from('user_settings')
      .select('youtube_refresh_token, youtube_sub_refresh_token')
      .eq('user_id', user.id)
      .single();

    const refreshToken = channelType === 'sub' ? settings?.youtube_sub_refresh_token : settings?.youtube_refresh_token;

    if (!refreshToken) {
      return NextResponse.json({ error: `YouTube ${channelType} account not connected` }, { status: 400 });
    }

    // Setup YouTube client
    const oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID,
      process.env.GOOGLE_CLIENT_SECRET,
      `${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/api/youtube/callback`
    );
    oauth2Client.setCredentials({ refresh_token: refreshToken });
    const youtube = google.youtube({ version: 'v3', auth: oauth2Client });

    // Download video locally for upload
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'yt-upload-'));
    const safeStoryId = sanitizePathComponent(String(storyId));
    const videoPath = path.join(tmpDir, `video_${safeStoryId}.mp4`);
    
    console.log('Downloading video for YouTube upload...');
    await downloadFile(story.video_url, videoPath);

    // Compile description from scenes
    const sortedScenes = (story.scenes || []).sort((a: any, b: any) => a.scene_number - b.scene_number);
    let fullScript = sortedScenes.map((s: any) => `Scene ${s.scene_number}:\n${s.script}`).join('\n\n');

    // YouTube Limits: Title (100 chars), Description (5000 chars)
    let videoTitle = story.title || 'AI Generated Storyboard';
    if (videoTitle.length > 95) {
      videoTitle = videoTitle.substring(0, 95) + '...';
    }

    let videoDescription = `Generated by AI Storyboard Generator\n\n${fullScript}`;
    if (videoDescription.length > 4900) {
      videoDescription = videoDescription.substring(0, 4900) + '...';
    }

    console.log('Uploading to YouTube...');
    const res = await youtube.videos.insert({
      part: ['snippet', 'status'],
      requestBody: {
        snippet: {
          title: videoTitle,
          description: videoDescription,
          tags: ['AI', 'Storyboard', 'AI Video'],
        },
        status: {
          privacyStatus: 'private',
        },
      },
      media: {
        body: fs.createReadStream(videoPath),
      },
    });

    const videoId = res.data.id;
    const youtubeUrl = `https://www.youtube.com/watch?v=${videoId}`;

    // Update story in DB
    await supabase
      .from('stories')
      .update({ youtube_url: youtubeUrl })
      .eq('id', storyId);

    return NextResponse.json({ success: true, youtubeUrl });

  } catch (error: any) {
    console.error('YouTube upload error:', error);
    
    const errorMessage = error.message || error?.response?.data?.error;
    if (errorMessage === 'invalid_grant' || errorMessage === 'unauthorized_client') {
      if (userId && supabaseClient) {
        const updateData = currentChannelType === 'sub' 
          ? { youtube_sub_refresh_token: null }
          : { youtube_refresh_token: null };
          
        await supabaseClient
          .from('user_settings')
          .update(updateData)
          .eq('user_id', userId);
      }
      return NextResponse.json({ error: `YouTube authorization failed or expired. Please reconnect your ${currentChannelType} account.` }, { status: 401 });
    }

    return NextResponse.json({ error: error.message || 'Failed to upload video to YouTube' }, { status: 500 });
  } finally {
    if (tmpDir) {
      try {
        fs.rmSync(tmpDir, { recursive: true, force: true });
      } catch (e) {
        console.warn('Failed to remove temp directory:', e);
      }
    }
  }
}
