import { NextRequest, NextResponse } from 'next/server';
import { google } from 'googleapis';
import { createServerClient } from '@supabase/ssr';
import fs from 'fs';
import path from 'path';
import os from 'os';

// Helper to download the video locally
async function downloadFile(url: string, outputPath: string) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.statusText}`);
  
  const arrayBuffer = await response.arrayBuffer();
  fs.writeFileSync(outputPath, new Uint8Array(arrayBuffer));
}

export async function POST(request: NextRequest) {
  let userId: string | null = null;
  let currentChannelType = 'main';
  let supabaseClient: any = null;

  try {
    const { storyId, channelType = 'main' } = await request.json();
    currentChannelType = channelType;
    if (!storyId) return NextResponse.json({ error: 'storyId is required' }, { status: 400 });

    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() {
            return request.cookies.getAll();
          },
          setAll() {},
        },
      }
    );
    supabaseClient = supabase;

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    userId = user.id;

    // Get YouTube refresh token
    const { data: settings } = await supabase
      .from('user_settings')
      .select('youtube_refresh_token, youtube_sub_refresh_token')
      .eq('user_id', user.id)
      .single();

    const refreshToken = channelType === 'sub' ? settings?.youtube_sub_refresh_token : settings?.youtube_refresh_token;

    if (!refreshToken) {
      return NextResponse.json({ error: `YouTube ${channelType} account not connected` }, { status: 400 });
    }

    // Get Story Data
    const { data: story } = await supabase
      .from('stories')
      .select('*, scenes(*)')
      .eq('id', storyId)
      .single();

    if (!story || !story.video_url) {
      return NextResponse.json({ error: 'Story or video not found' }, { status: 404 });
    }

    // Setup YouTube client
    const oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID,
      process.env.GOOGLE_CLIENT_SECRET,
      `${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/api/youtube/callback`
    );
    oauth2Client.setCredentials({ refresh_token: refreshToken });
    const youtube = google.youtube({ version: 'v3', auth: oauth2Client });

    // Download video locally for upload
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'yt-upload-'));
    const videoPath = path.join(tmpDir, `video_${storyId}.mp4`);
    
    console.log('Downloading video for YouTube upload...');
    await downloadFile(story.video_url, videoPath);

    // Compile description from scenes
    const sortedScenes = story.scenes.sort((a: any, b: any) => a.scene_number - b.scene_number);
    let fullScript = sortedScenes.map((s: any) => `Scene ${s.scene_number}:\n${s.script}`).join('\n\n');

    // YouTube Limits: Title (100 chars), Description (5000 chars)
    let videoTitle = story.title || 'AI Generated Storyboard';
    if (videoTitle.length > 95) {
      videoTitle = videoTitle.substring(0, 95) + '...';
    }

    let videoDescription = `Generated by AI Storyboard Generator\n\n${fullScript}`;
    if (videoDescription.length > 4900) {
      videoDescription = videoDescription.substring(0, 4900) + '...';
    }

    console.log('Uploading to YouTube...');
    const res = await youtube.videos.insert({
      part: ['snippet', 'status'],
      requestBody: {
        snippet: {
          title: videoTitle,
          description: videoDescription,
          tags: ['AI', 'Storyboard', 'AI Video'],
        },
        status: {
          privacyStatus: 'private', // User requested private first
        },
      },
      media: {
        body: fs.createReadStream(videoPath),
      },
    });

    const videoId = res.data.id;
    const youtubeUrl = `https://www.youtube.com/watch?v=${videoId}`;

    // Clean up temp file
    fs.rmSync(tmpDir, { recursive: true, force: true });

    // Update story in DB
    await supabase
      .from('stories')
      .update({ youtube_url: youtubeUrl })
      .eq('id', storyId);

    return NextResponse.json({ success: true, youtubeUrl });

  } catch (error: any) {
    console.error('YouTube upload error:', error);
    
    const errorMessage = error.message || error?.response?.data?.error;
    if (errorMessage === 'invalid_grant' || errorMessage === 'unauthorized_client') {
      if (userId && supabaseClient) {
        const updateData = currentChannelType === 'sub' 
          ? { youtube_sub_refresh_token: null }
          : { youtube_refresh_token: null };
          
        await supabaseClient
          .from('user_settings')
          .update(updateData)
          .eq('user_id', userId);
      }
      return NextResponse.json({ error: `YouTube authorization failed or expired. Please reconnect your ${currentChannelType} account.` }, { status: 401 });
    }

    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
