import { NextRequest, NextResponse } from 'next/server';
import { GenerateImagesSchema } from '@/lib/validations';
import { getAuthenticatedUser, verifyStoryOwnership, validateMediaUrl } from '@/lib/auth-helpers';

export async function POST(request: NextRequest) {
  try {
    // 1. Authenticate user
    const { supabase, user } = await getAuthenticatedUser(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // 2. Validate input
    let body: any;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ error: 'Invalid JSON payload' }, { status: 400 });
    }

    const validation = GenerateImagesSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { error: validation.error.errors[0]?.message || 'Validation error' },
        { status: 400 }
      );
    }

    const { storyId, sceneId, retryFailed } = validation.data;

    // 3. Authorize story ownership (IDOR check)
    const story = await verifyStoryOwnership(supabase, storyId, user.id);
    if (!story) {
      return NextResponse.json({ error: 'Story not found or unauthorized' }, { status: 404 });
    }

    if (!process.env.TOGETHER_API_KEY) {
      return NextResponse.json(
        { error: 'Together AI API key is not configured on the server' },
        { status: 500 }
      );
    }

    if (retryFailed) {
      await supabase
        .from('scenes')
        .update({ image_status: 'pending' })
        .eq('story_id', storyId)
        .eq('image_status', 'failed');
    }

    let query = supabase
      .from('scenes')
      .select('*')
      .eq('story_id', storyId);

    if (sceneId) {
      query = query.eq('id', sceneId);
    } else {
      query = query.eq('image_status', 'pending');
    }

    const { data: scenes, error: scenesError } = await query.order('scene_number', { ascending: true });

    if (scenesError) {
      throw scenesError;
    }

    if (!scenes || scenes.length === 0) {
      return NextResponse.json({
        success: true,
        message: 'No pending scenes to generate images for',
      });
    }

    for (const scene of scenes) {
      try {
        await supabase
          .from('scenes')
          .update({ image_status: 'generating' })
          .eq('id', scene.id);

        let response: Response | undefined;
        let retries = 3;
        let lastError: Error | null = null;
        
        // Define primary and fallback models
        const models = [
          'black-forest-labs/FLUX.1-schnell',
          'stabilityai/stable-diffusion-xl-base-1.0'
        ];

        for (let i = 0; i < retries; i++) {
          const currentModel = models[Math.min(i, models.length - 1)];
          
          try {
            response = await fetch('https://api.together.xyz/v1/images/generations', {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${process.env.TOGETHER_API_KEY}`,
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                model: currentModel,
                prompt: `${scene.image_prompt}. Cinematic, high quality, detailed, 16:9 aspect ratio`,
                width: 1024,
                height: 576,
                steps: 4,
                n: 1,
              }),
            });

            if (!response.ok) {
              const errorText = await response.text();
              throw new Error(`Together AI API error: ${response.status} ${response.statusText} - ${errorText}`);
            }
            
            break;
          } catch (error: any) {
            lastError = error;
            console.warn(`Attempt ${i + 1} failed for scene ${scene.id} using model ${currentModel}: ${error.message}`);
            if (i < retries - 1) {
              await new Promise((resolve) => setTimeout(resolve, 2000 * (i + 1)));
            }
          }
        }

        if (!response || !response.ok) {
          throw lastError || new Error(`Together AI API failed after ${retries} attempts`);
        }

        const data = await response.json();
        const ephemeralUrl = data.data?.[0]?.url;

        if (ephemeralUrl) {
          if (!validateMediaUrl(ephemeralUrl)) {
            throw new Error('Invalid ephemeral image URL generated by AI provider');
          }

          const imgResponse = await fetch(ephemeralUrl);
          if (!imgResponse.ok) throw new Error('Failed to download image from Together AI');
          
          const arrayBuffer = await imgResponse.arrayBuffer();
          const buffer = Buffer.from(arrayBuffer);
          const fileName = `story_${storyId}_scene_${scene.id}.png`;

          const { error: uploadError } = await supabase.storage
            .from('media')
            .upload(fileName, buffer, {
              contentType: 'image/png',
              upsert: true,
            });

          if (uploadError) throw uploadError;

          const { data: publicUrlData } = supabase.storage
            .from('media')
            .getPublicUrl(fileName);

          const permanentUrl = publicUrlData.publicUrl;

          await supabase
            .from('scenes')
            .update({
              image_url: permanentUrl,
              image_status: 'completed',
            })
            .eq('id', scene.id);
        } else {
          throw new Error('No image URL returned');
        }

        await new Promise((resolve) => setTimeout(resolve, 1000));
      } catch (error: any) {
        console.error(`Error generating image for scene ${scene.id}:`, error);

        await supabase
          .from('scenes')
          .update({ image_status: 'failed' })
          .eq('id', scene.id);
      }
    }

    const { count } = await supabase
      .from('scenes')
      .select('*', { count: 'exact', head: true })
      .eq('story_id', storyId)
      .eq('image_status', 'pending');

    return NextResponse.json({
      success: true,
      processedScenes: scenes.length,
      morePending: (count || 0) > 0,
      totalPending: count || 0,
    });
  } catch (error: any) {
    console.error('Error generating images:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to generate images' },
      { status: 500 }
    );
  }
}
